In [3]:
import numpy as np

In [2]:
sarasas = [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
masyvas = np.array(sarasas)
print(masyvas)

[1 2 3 4 5 6 7 8 9]


In [12]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
nuliai = np.zeros(10)
nuliai

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
vienetai = np.ones(10)
vienetai

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
ketvertai = np.ones(10) * 4
ketvertai

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [17]:
imtis = np.arange(0, 101, 2)
imtis

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [8]:
vienas_penki = np.arange(1, 26)
shape = vienas_penki.reshape(5,5)
shape

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
shape[2, 1]

12

In [14]:
shape[4,0:5]

array([21, 22, 23, 24, 25])

In [25]:
shape[0:3, 0:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [35]:
shape[1:4,1:5]

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

In [41]:
shape[3:5,0:3]

array([[16, 17, 18],
       [21, 22, 23]])

In [4]:
atsitiktinis = np.random.rand(20)
atsitiktinis

array([0.14934189, 0.68715206, 0.76055645, 0.61872907, 0.35345689,
       0.88605383, 0.39097993, 0.66343244, 0.3945316 , 0.71195393,
       0.65313192, 0.5954525 , 0.50191504, 0.94176311, 0.32576019,
       0.84873115, 0.98062218, 0.15821164, 0.8418579 , 0.3012074 ])

In [59]:
atsitiktinis.max()

0.9887542468196573

In [60]:
atsitiktinis.min()

0.006235907662603513

In [5]:
atsitiktinis.dtype

dtype('float64')

In [26]:
vektorius = np.arange(1, 101)

In [20]:
daugiau = vektorius > 90
vektorius[daugiau]

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [28]:
vektorius[vektorius % 7==0 ]


array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [29]:
np.linspace(0.025,1,40).reshape(5,8) #nuo 0.025 iki 1 padar 40 daliu

array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
       [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
       [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
       [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
       [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])

In [34]:
matrica = np.arange(2, 1000)
res = matrica[(matrica ** 0.5) % 1 == 0].reshape(6,5)
res

array([[  4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256],
       [289, 324, 361, 400, 441],
       [484, 529, 576, 625, 676],
       [729, 784, 841, 900, 961]])