In [3]:
import numpy as np

In [2]:
sarasas = [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
masyvas = np.array(sarasas)
print(masyvas)

[1 2 3 4 5 6 7 8 9]


In [12]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
nuliai = np.zeros(10)
nuliai

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
vienetai = np.ones(10)
vienetai

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
ketvertai = np.ones(10) * 4
ketvertai

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [17]:
imtis = np.arange(0, 101, 2)
imtis

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [8]:
vienas_penki = np.arange(1, 26)
shape = vienas_penki.reshape(5,5)
shape

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
shape[2, 1]

12

In [14]:
shape[4,0:5]

array([21, 22, 23, 24, 25])

In [25]:
shape[0:3, 0:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [35]:
shape[1:4,1:5]

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

In [41]:
shape[3:5,0:3]

array([[16, 17, 18],
       [21, 22, 23]])

In [58]:
atsitiktinis = np.random.rand(20)
atsitiktinis

array([0.31747909, 0.46883323, 0.98875425, 0.24967502, 0.04626961,
       0.62900674, 0.24231739, 0.34080369, 0.69499305, 0.76805357,
       0.15133976, 0.17366594, 0.04303351, 0.50371524, 0.46271386,
       0.00623591, 0.44618143, 0.34576695, 0.68933059, 0.16939543])

In [59]:
atsitiktinis.max()

0.9887542468196573

In [60]:
atsitiktinis.min()

0.006235907662603513