In [1]:
import numpy as np

In [3]:
sarasas = [4, 7, 11, 6, 9, 69, 420, 777, 31]

In [4]:
masyvas = np.array(sarasas) #np masyvas, sarasa reikia paversti np masyvu array
print(masyvas, type(masyvas))

[  4   7  11   6   9  69 420 777  31] <class 'numpy.ndarray'>


In [7]:
sugrupuota = [[4, 7, 11],[6, 9, 69], [420, 777, 31]]

In [8]:
matrica = np.array(sugrupuota)
print(matrica)

[[  4   7  11]
 [  6   9  69]
 [420 777  31]]


In [9]:
imtis = np.arange(0, 30, 3)
print(imtis, type(imtis))

[ 0  3  6  9 12 15 18 21 24 27] <class 'numpy.ndarray'>


In [ ]:
#dar masyva vadina vektoriumi

In [10]:
nuliai = np.zeros(10)
print(nuliai)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
nuliai_6x6 = np.zeros((6, 6))
nuliai_6x6

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
akis = np.eye(6)
akis

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [14]:
#kaip pasiekti matricos elementa
akis[1][2]

0.0

In [15]:
akis[0][1] = 3
akis[1][0] = 2
akis

array([[1., 3., 0., 0., 0., 0.],
       [2., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [18]:
np.linspace(2, 10, 5) #nuo vieno iki vienuolikos padalina 10 i 5 dalis

array([ 2.,  4.,  6.,  8., 10.])

In [19]:
np.linspace(0, 1, 3)

array([0. , 0.5, 1. ])

In [20]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [ ]:
#random arrays

In [28]:
np.random.rand(10) #10 atsitiktiniu skaiciu

array([0.31908049, 0.18397501, 0.07752751, 0.81585151, 0.86907128,
       0.87759289, 0.54783556, 0.50415112, 0.06277495, 0.48793926])

In [22]:
np.random.rand(5, 5)

array([[0.46510617, 0.49121617, 0.15225267, 0.61074937, 0.77155842],
       [0.10971443, 0.40294142, 0.69971646, 0.18328189, 0.16674058],
       [0.33113191, 0.96904137, 0.95850859, 0.00885098, 0.68513446],
       [0.50933282, 0.52568673, 0.66758565, 0.75976703, 0.31566829],
       [0.00522822, 0.42908864, 0.97811288, 0.68031005, 0.6809779 ]])

In [24]:
np.random.randn(5, 5) * 100 #atsitiktinius skaicius daugina is 100

array([[-105.32144658,  -76.18148032,  -88.49337244,   14.34790143,
          80.62654356],
       [  79.80343129,  -28.95090467,  -70.18934537,  -39.80614742,
          63.53074954],
       [  73.04881247, -145.98851257,  -98.90730176,   40.07659539,
          30.54118946],
       [-106.07479909, -171.16318615,  -26.63211563, -165.64521107,
          46.03689973],
       [  11.08940732,   40.70788285,  -36.21275457,  135.34056895,
          89.52388393]])

In [29]:
np.random.randint(100, 200, 10)

array([188, 173, 141, 102, 105, 149, 106, 122, 128, 182])

In [ ]:
#masyvu pertvarkymas

In [31]:
betko_64 = np.random.randint(100, 999, 64) #bet kokie 64 skaicia
betko_64

array([163, 727, 112, 381, 812, 523, 903, 543, 265, 117, 640, 356, 701,
       826, 803, 320, 967, 373, 677, 554, 433, 860, 196, 234, 780, 124,
       397, 260, 506, 290, 203, 546, 916, 235, 948, 272, 519, 135, 411,
       327, 671, 384, 713, 395, 118, 883, 550, 629, 670, 431, 813, 178,
       120, 765, 421, 905, 102, 796, 639, 802, 783, 330, 844, 653])

In [32]:
betko_8x8 = betko_64.reshape(8, 8)
print(betko_8x8)

[[163 727 112 381 812 523 903 543]
 [265 117 640 356 701 826 803 320]
 [967 373 677 554 433 860 196 234]
 [780 124 397 260 506 290 203 546]
 [916 235 948 272 519 135 411 327]
 [671 384 713 395 118 883 550 629]
 [670 431 813 178 120 765 421 905]
 [102 796 639 802 783 330 844 653]]


In [33]:
#netaisiklinga matrica
betko_20 = np.random.randint(100, 999, 20)
betko_4x5 = betko_20.reshape(4, 5)
print(betko_4x5) #skiraisi eiluciu ir stulpeliu skaicius

[[968 366 541 560 756]
 [404 421 709 745 237]
 [443 744 204 309 954]
 [761 411 457 993 846]]


In [ ]:
#naudingi metodai

In [34]:
print(min(betko_64)) #python min
print(betko_64.min()) #np min

102
102


In [35]:
betko_8x8.max()


967

In [37]:
print(betko_20.argmin(), betko_20.min()) #kurioje vietoje ir kokia reiksme, siuo atveju 12 vieta reiksme 204

12 204


In [38]:
betko_8x8.argmax()

16

In [40]:
kvadratas =  np.zeros((5, 5)).astype(int) + 1
print(kvadratas)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [41]:
betko_8x8.shape

(8, 8)

In [42]:
betko_4x5.dtype #parodo koks yra kintamuju tipas

dtype('int64')

In [ ]:
#indeksacija ir reiksmiu traukimas

In [43]:
betko_20

array([968, 366, 541, 560, 756, 404, 421, 709, 745, 237, 443, 744, 204,
       309, 954, 761, 411, 457, 993, 846])

In [44]:
betko_20[2]

541

In [45]:
betko_20[2:5]

array([541, 560, 756])

In [46]:
betko_20[::2]

array([968, 541, 756, 421, 745, 443, 204, 954, 411, 993])

In [47]:
betko_20[-5]= 777
betko_20

array([968, 366, 541, 560, 756, 404, 421, 709, 745, 237, 443, 744, 204,
       309, 954, 777, 411, 457, 993, 846])

In [48]:
betko_8x8

array([[163, 727, 112, 381, 812, 523, 903, 543],
       [265, 117, 640, 356, 701, 826, 803, 320],
       [967, 373, 677, 554, 433, 860, 196, 234],
       [780, 124, 397, 260, 506, 290, 203, 546],
       [916, 235, 948, 272, 519, 135, 411, 327],
       [671, 384, 713, 395, 118, 883, 550, 629],
       [670, 431, 813, 178, 120, 765, 421, 905],
       [102, 796, 639, 802, 783, 330, 844, 653]])

In [49]:
betko_8x8[2, 2]

677

In [51]:
betko_8x8[2,2:5] #pirmas yra y, antras x antroje eilute nuo 2 iki 5

array([677, 554, 433])

In [52]:
betko_8x8[2:-2, 2:-2]

array([[677, 554, 433, 860],
       [397, 260, 506, 290],
       [948, 272, 519, 135],
       [713, 395, 118, 883]])

In [53]:
betko_8x8[-3:,-3:]

array([[883, 550, 629],
       [765, 421, 905],
       [330, 844, 653]])

In [54]:
betko_4x5[-3:, -3:]

array([[709, 745, 237],
       [204, 309, 954],
       [457, 993, 846]])

In [ ]:
#reiksmiu traukimas pagal salyga

In [55]:
tiesa_8x8 = betko_8x8 > 500
tiesa_8x8

array([[False,  True, False, False,  True,  True,  True,  True],
       [False, False,  True, False,  True,  True,  True, False],
       [ True, False,  True,  True, False,  True, False, False],
       [ True, False, False, False,  True, False, False,  True],
       [ True, False,  True, False,  True, False, False, False],
       [ True, False,  True, False, False,  True,  True,  True],
       [ True, False,  True, False, False,  True, False,  True],
       [False,  True,  True,  True,  True, False,  True,  True]])

In [56]:
betko_8x8[tiesa_8x8]

array([727, 812, 523, 903, 543, 640, 701, 826, 803, 967, 677, 554, 860,
       780, 506, 546, 916, 948, 519, 671, 713, 883, 550, 629, 670, 813,
       765, 905, 796, 639, 802, 783, 844, 653])

In [65]:
dideli = betko_8x8[tiesa_8x8]

In [57]:
betko_8x8[betko_8x8 < 200]

array([163, 112, 117, 196, 124, 135, 118, 178, 120, 102])

In [66]:
dideli.shape

(34,)

In [67]:
dideli.reshape(17, 2)

array([[727, 812],
       [523, 903],
       [543, 640],
       [701, 826],
       [803, 967],
       [677, 554],
       [860, 780],
       [506, 546],
       [916, 948],
       [519, 671],
       [713, 883],
       [550, 629],
       [670, 813],
       [765, 905],
       [796, 639],
       [802, 783],
       [844, 653]])

In [ ]:
#elgsenos ypatumai

In [68]:
betko_20

array([968, 366, 541, 560, 756, 404, 421, 709, 745, 237, 443, 744, 204,
       309, 954, 777, 411, 457, 993, 846])

In [70]:
ispjova = betko_20[5: -5]
ispjova

array([404, 421, 709, 745, 237, 443, 744, 204, 309, 954])

In [71]:
ispjova[:] = 999 #visus narius keiciame i 999, bet pradzioje reikia persitvarkyti, nes kitaip duos ir senas reiksmes

In [76]:
betko_20

array([968, 366, 541, 560, 756, 999, 999, 999, 999, 999, 999, 999, 999,
       999, 999, 777, 411, 457, 993, 846])

In [86]:
kopija = betko_20.copy()
kopija


array([968, 366, 541, 560, 756, 999, 999, 999, 999, 999, 999, 999, 999,
       999, 999, 777, 411, 457, 993, 846])

In [87]:
kopija == betko_20 #turi buti tiesa

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [88]:
kopija_ispjova = kopija[5:-5]
kopija_ispjova

array([999, 999, 999, 999, 999, 999, 999, 999, 999, 999])

In [89]:
kopija_ispjova[:] = np.random.randint(100, 999, 10)

In [90]:
kopija

array([968, 366, 541, 560, 756, 861, 350, 726, 216, 252, 426, 255, 534,
       537, 205, 777, 411, 457, 993, 846])

In [91]:
kopija == betko_20

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [ ]:
#matematines operacijos

In [92]:
pirmi_10 = np.random.randint(0, 99, 10)
antri_10 = np.random.randint(0, 99, 10)
print(pirmi_10, antri_10)

[56 68 52 62 63 60 64 77  1 44] [30 80 79 52 95 27 28 62 76 15]


In [93]:
sudetis = pirmi_10 + antri_10
sudetis

array([ 86, 148, 131, 114, 158,  87,  92, 139,  77,  59])

In [94]:
daugyba= (pirmi_10 * antri_10)
daugyba

array([1680, 5440, 4108, 3224, 5985, 1620, 1792, 4774,   76,  660])

In [95]:
dalyba = (antri_10 / pirmi_10)
dalyba

array([ 0.53571429,  1.17647059,  1.51923077,  0.83870968,  1.50793651,
        0.45      ,  0.4375    ,  0.80519481, 76.        ,  0.34090909])

In [96]:
kubu = pirmi_10 ** 3
kubu

array([175616, 314432, 140608, 238328, 250047, 216000, 262144, 456533,
            1,  85184])

In [97]:
kubu = pirmi_10 ** 30 #jeigu yra - (minusai) tai perlipa sistemos ribas ir nebeskaiciuoja
kubu

array([                   0,  1152921504606846976, -8070450532247928832,
        4988354582640852992,  8055827235060000897,  1152921504606846976,
                          0,  1417994635528012185,                    1,
       -8070450532247928832])

In [98]:
np.sin(pirmi_10)

array([-0.521551  , -0.89792768,  0.98662759, -0.7391807 ,  0.1673557 ,
       -0.30481062,  0.92002604,  0.99952016,  0.84147098,  0.01770193])

In [99]:
np.log(pirmi_10)

array([4.02535169, 4.21950771, 3.95124372, 4.12713439, 4.14313473,
       4.09434456, 4.15888308, 4.34380542, 0.        , 3.78418963])

In [100]:
print(pirmi_10, np.log(pirmi_10))

[56 68 52 62 63 60 64 77  1 44] [4.02535169 4.21950771 3.95124372 4.12713439 4.14313473 4.09434456
 4.15888308 4.34380542 0.         3.78418963]
